# Generated by Django 3.2.9 on 2021-11-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_song_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='writer',
            new_name='writers',
        ),
    ]
