# Generated by Django 3.2.9 on 2021-11-24 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_album_band'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app.artist', verbose_name='Artist'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('band', 'artist')},
        ),
    ]
