# Generated by Django 3.2.9 on 2021-11-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211124_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='writers',
            field=models.ManyToManyField(related_name='songs', to='app.Artist', verbose_name='Writer'),
        ),
    ]
